### ISSUE TITLE
combining mask_subtract results into single gff for family analysis?

### ISSUE THREAD

**Issue by steichten** [mcstitzer/maize_v4_TE_annotation#1]
This is good stuff. Just trying to adapt this pipeline to Brachypodium. After burning through the mask_subtract iterations and the replacement of proper genomic coordinates, is there a step to be merging these proper coordinate gff files together for the family level analysis? I assume as much, but I want to make sure I'm not missing something.

**Comment by mcstitzer** [comment]
Yes, sorry! Script is now added, as done for v4.

https://github.com/mcstitzer/maize_v4_TE_annotation/blob/master/ltr/combine_all_gffs_and_assign_fams.R
