### ISSUE TITLE
silix error

### ISSUE THREAD

**Issue by Kapeel** [mcstitzer/maize_v4_TE_annotation#3]
Hi,

The silix run command on the shell scripts seems to be missing a argument 
```
# single linkage cluster those that are 80% identical to each other.
$SILIX ${GENOME}-matches.noTSD.fa -f SINE -i 0.8 -r 0.8 > ${GENOME}-matches.noTSD.8080.fnodes
```
When I run the run_sines.sh, I get the following error:
```
silix -f SINE -i 0.8 -r 0.8 ${GENOME}-matches.noTSD.fa 
error: uncorrect number of command line arguments
```

I installed the new version of silix http://lbbe.univ-lyon1.fr/Documentation.html?lang=fr
here it shows the inputs as fasta file and a result file(s) of a all-against-all BLAST search in tabular format. 

I tried using vsearch to identify homology and use the generated ${GENOME}-matches.noTSD.allvall.8080.out with silix. It gives another error

```
silix ki11-matches.noTSD.fa ${GENOME}-matches.noTSD.allvall.8080.out -f FAM -i 0.8 -r 0.8 
Error in Fam : unable to open file Contig0_905257967_905258098_F_TSDlen13_TSDscore10_TSDmism3
```
Appreciate any help.

Thanks

Kapeel

**Comment by mcstitzer** [comment]
Added vsearch output (`${GENOME}-matches.noTSD.allvall.8080.out`) as argument for silix in `run_sines.sh`.
