### ISSUE TITLE
Helitron Scanner error

### ISSUE THREAD

**Issue by Kapeel** [mcstitzer/maize_v4_TE_annotation#6]
Hi,

I had to modify run_helitron_scanner.sh in few places to make the script run, but still ended up with a few errors. I am running 10 test scaffolds from Maize assembly. 

-  for -g $GENOMEFA (line 25, 27), the variable $GENOMEFA is not defined in the script, replaced it with $GENOMEFASTA

- for -g ../$GENOME (line 33, 41,43,49) should be replaced with $GENOMEFASTA

- line 67 $USEARCH should be $VSEARCH

With the above corrections I ended with the below error
```
        [1:27729]    [Wed Apr 04 10:48:53 CDT 2018]
# All finished.    [Wed Apr 04 10:48:54 CDT 2018]
vsearch v2.6.2_linux_x86_64, 15.7GB RAM, 6 cores
https://github.com/torognes/vsearch

Reading file kill.last_10scf.HelitronScanner.tabnames.fa 100%  
41064 nt in 9 seqs, min 870, max 10721, avg 4563
Masking 100% 
Aligning 100%  
Matching query sequences: 1 of 9 (11.11%)
Error in Fam : unable to open file Contig3636_21537_22481
```

**Comment by mcstitzer** [comment]
Updated the $GENOMEFA and $VSEARCH references. Error seemed to result from silix, downloading and recompiling it worked (with both versions [1.2.9](ftp://pbil.univ-lyon1.fr/pub/logiciel/silix/silix-1.2.9.tar.gz) which I originally used, and the newest [1.2.11](ftp://pbil.univ-lyon1.fr/pub/logiciel/silix/silix-1.2.11.tar.gz)).
