### ISSUE TITLE
Sine

### ISSUE THREAD

**Issue by Kapeel** [mcstitzer/maize_v4_TE_annotation#8]
When I run `sh run_sines.sh`
I get below error on line 22 
`python sine_finder.py -T chunkwise -V1 -f both -o FR ../${GENOMEFASTA}`
But looks like -o FR is a valid parmater.

```sine_finder_version=1.0.1

ERROR 02: wrong or missing option for '-o'
mv: cannot stat ‘../kill.last_10scf-matches.fasta’: No such file or directory
mv: cannot stat ‘../kill.last_10scf-matches.csv’: No such file or directory
```

Kapeel

**Comment by mcstitzer** [comment]
Altered `run_sines.sh` to remove -o option, and instead use defaults. Seems to be an issue with Sine Finder, which doesn't make use of the -o parameter.
