### ISSUE TITLE
MTEC Links Broken

### ISSUE THREAD

**Issue by rajewski** [mcstitzer/maize_v4_TE_annotation#9]
Many of the scripts point to reference fasta files that were available from the MTEC. This website has been down for a while, is there an alternative host for these reference files?

**Comment by blavetn** [comment]
Hello, here a link to the file TE_12-Feb-2015_15-35.fa
https://drive.google.com/file/d/15rQlgONFUCU2HMOU7uzog-rLxILrZweE/view?usp=sharing

**Comment by ttian627** [comment]
The link is lost, can you provide a new link for the file TE_12-Feb-2015_15-35.fa?

**Comment by ttian627** [comment]
where can I download the "te_reference_fasta" folder?

**Comment by blavetn** [comment]
The google drive link I have provided to the file TE_12-Feb-2015_15-35.fa is working... I have just tested it.

**Comment by ttian627** [comment]
Can you send me the file? I can not access it. My Email address is ttian627@163.com. Thank you very much!

**Comment by blavetn** [comment]
Try this link:
https://github.com/mcstitzer/dawe_ab10_kindr/blob/master/identify_haplotypes/te_alignments/TE_12-Feb-2015_15-35.fa

**Comment by ttian627** [comment]
Okay, I've downloaded it. Thank you again.
